---
apiVersion: v1
kind: Secret
metadata:
  name: scaleway-api-key
  namespace: kube-system
stringData:
  SCW_ACCESS_KEY: SCWxxxx
  SCW_SECRET_KEY: xxxx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["endpoints", "pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.15.0
        args:
        - --provider=scaleway
        - --source=node
        - --source=service
        - --zone-name-filter=kube.arno-scw.fr
        - --domain-filter=kube.arno-scw.fr
        - --fqdn-template=udp.kube.arno-scw.fr
        - --label-filter=external-dns.alpha.kubernetes.io/publish==true
        - --registry=txt
        - --txt-owner-id=udp-ha-test # Unique identifier for the cluster in the domain, can be its name or id
        - --events
        - --interval=5m # Longer pooling but events trigger updates
        - --policy=sync
        - --log-level=info
        env:
        - name: SCW_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: scaleway-api-key
              key: SCW_ACCESS_KEY
        - name: SCW_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: scaleway-api-key
              key: SCW_SECRET_KEY
